<a href="https://colab.research.google.com/github/NavyasriAmalapurapu/Navyasri/blob/main/movies_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/movies.csv')

In [ ]:
data

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,18.433,8.7,2763
1,1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,8.439,8.7,1223
2,2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,65.570,8.7,18637
3,3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,63.277,8.7,14052
4,4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,26.691,8.7,773
...,...,...,...,...,...,...,...,...
8546,8546,13805,Disaster Movie,"The filmmaking team behind the hits ""Scary Mov...",2008-08-29,14.630,3.2,714
8547,8547,5491,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,10.647,3.0,543
8548,8548,14164,Dragonball Evolution,The young warrior Son Goku sets out on a quest...,2009-03-12,32.244,2.8,1447
8549,8549,11059,House of the Dead,"Set on an island off the coast, a techno rave ...",2003-04-11,14.502,2.8,238
8550,8550,40016,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,2010-02-27,9.824,2.2,215

In [ ]:
data.head(10)

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,18.433,8.7,2763
1,1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,8.439,8.7,1223
2,2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,65.570,8.7,18637
3,3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,63.277,8.7,14052
4,4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,26.691,8.7,773
5,5,696374,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,2020-05-29,10.510,8.7,1993
6,6,791373,Zack Snyder's Justice League,Determined to ensure Superman's ultimate sacri...,2021-03-18,7337.834,8.6,4179
7,7,399566,Godzilla vs. Kong,"In a time when monsters walk the Earth, humani...",2021-03-24,11701.435,8.7,1236
8,8,441130,Wolfwalkers,"In a time of superstition and magic, when wolv...",2020-10-26,30.109,8.6,354
9,9,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-11-30,37.478,8.6,11179

In [ ]:
data.tail(10)

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
8541,8541,9544,FearDotCom,When four bodies are discovered among the indu...,2002-08-09,11.379,3.7,254
8542,8542,485774,The Open House,A teenager and his mother find themselves besi...,2018-01-19,13.053,3.7,1105
8543,8543,35885,Amore 14,"Come ogni 14enne Carolina, detta Caro,è impegn...",2009-10-30,7.632,3.6,231
8544,8544,12142,Alone in the Dark,Edward Carnby is a private investigator specia...,2005-01-28,16.222,3.3,398
8545,8545,74849,The Star Wars Holiday Special,Luke Skywalker and Han Solo battle evil Imperi...,1978-12-01,9.966,3.2,309
8546,8546,13805,Disaster Movie,"The filmmaking team behind the hits ""Scary Mov...",2008-08-29,14.630,3.2,714
8547,8547,5491,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,10.647,3.0,543
8548,8548,14164,Dragonball Evolution,The young warrior Son Goku sets out on a quest...,2009-03-12,32.244,2.8,1447
8549,8549,11059,House of the Dead,"Set on an island off the coast, a techno rave ...",2003-04-11,14.502,2.8,238
8550,8550,40016,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,2010-02-27,9.824,2.2,215

In [ ]:
data.add

<bound method DataFrame.add of       Unnamed: 0      id                        title  \
0              0   19404  Dilwale Dulhania Le Jayenge
1              1  724089    Gabriel's Inferno Part II
2              2     278     The Shawshank Redemption
3              3     238                The Godfather
4              4  761053   Gabriel's Inferno Part III
...          ...     ...                          ...
8546        8546   13805               Disaster Movie
8547        8547    5491            Battlefield Earth
8548        8548   14164         Dragonball Evolution
8549        8549   11059            House of the Dead
8550        8550   40016   Birdemic: Shock and Terror

                                               overview release_date  \
0     Raj is a rich, carefree, happy-go-lucky second...   1995-10-20
1     Professor Gabriel Emerson finally learns the t...   2020-07-31
2     Framed in the 1940s for the double murder of h...   1994-09-23
3     Spanning the years 1945 to 1955, a chronicle o...   1972-03-14
4     The final part of the film adaption of the ero...   2020-11-19
...                                                 ...          ...
8546  The filmmaking team behind the hits "Scary Mov...   2008-08-29
8547  In the year 3000, man is no match for the Psyc...   2000-05-12
8548  The young warrior Son Goku sets out on a quest...   2009-03-12
8549  Set on an island off the coast, a techno rave ...   2003-04-11
8550  A platoon of eagles and vultures attacks the r...   2010-02-27

      popularity  vote_average  vote_count
0         18.433           8.7        2763
1          8.439           8.7        1223
2         65.570           8.7       18637
3         63.277           8.7       14052
4         26.691           8.7         773
...          ...           ...         ...
8546      14.630           3.2         714
8547      10.647           3.0         543
8548      32.244           2.8        1447
8549      14.502           2.8         238
8550       9.824           2.2         215

[8551 rows x 8 columns]>

In [ ]:
data.all

<bound method DataFrame.all of       Unnamed: 0      id                        title  \
0              0   19404  Dilwale Dulhania Le Jayenge
1              1  724089    Gabriel's Inferno Part II
2              2     278     The Shawshank Redemption
3              3     238                The Godfather
4              4  761053   Gabriel's Inferno Part III
...          ...     ...                          ...
8546        8546   13805               Disaster Movie
8547        8547    5491            Battlefield Earth
8548        8548   14164         Dragonball Evolution
8549        8549   11059            House of the Dead
8550        8550   40016   Birdemic: Shock and Terror

                                               overview release_date  \
0     Raj is a rich, carefree, happy-go-lucky second...   1995-10-20
1     Professor Gabriel Emerson finally learns the t...   2020-07-31
2     Framed in the 1940s for the double murder of h...   1994-09-23
3     Spanning the years 1945 to 1955, a chronicle o...   1972-03-14
4     The final part of the film adaption of the ero...   2020-11-19
...                                                 ...          ...
8546  The filmmaking team behind the hits "Scary Mov...   2008-08-29
8547  In the year 3000, man is no match for the Psyc...   2000-05-12
8548  The young warrior Son Goku sets out on a quest...   2009-03-12
8549  Set on an island off the coast, a techno rave ...   2003-04-11
8550  A platoon of eagles and vultures attacks the r...   2010-02-27

      popularity  vote_average  vote_count
0         18.433           8.7        2763
1          8.439           8.7        1223
2         65.570           8.7       18637
3         63.277           8.7       14052
4         26.691           8.7         773
...          ...           ...         ...
8546      14.630           3.2         714
8547      10.647           3.0         543
8548      32.244           2.8        1447
8549      14.502           2.8         238
8550       9.824           2.2         215

[8551 rows x 8 columns]>

In [ ]:
data.align

<bound method NDFrame.align of       Unnamed: 0      id                        title  \
0              0   19404  Dilwale Dulhania Le Jayenge
1              1  724089    Gabriel's Inferno Part II
2              2     278     The Shawshank Redemption
3              3     238                The Godfather
4              4  761053   Gabriel's Inferno Part III
...          ...     ...                          ...
8546        8546   13805               Disaster Movie
8547        8547    5491            Battlefield Earth
8548        8548   14164         Dragonball Evolution
8549        8549   11059            House of the Dead
8550        8550   40016   Birdemic: Shock and Terror

                                               overview release_date  \
0     Raj is a rich, carefree, happy-go-lucky second...   1995-10-20
1     Professor Gabriel Emerson finally learns the t...   2020-07-31
2     Framed in the 1940s for the double murder of h...   1994-09-23
3     Spanning the years 1945 to 1955, a chronicle o...   1972-03-14
4     The final part of the film adaption of the ero...   2020-11-19
...                                                 ...          ...
8546  The filmmaking team behind the hits "Scary Mov...   2008-08-29
8547  In the year 3000, man is no match for the Psyc...   2000-05-12
8548  The young warrior Son Goku sets out on a quest...   2009-03-12
8549  Set on an island off the coast, a techno rave ...   2003-04-11
8550  A platoon of eagles and vultures attacks the r...   2010-02-27

      popularity  vote_average  vote_count
0         18.433           8.7        2763
1          8.439           8.7        1223
2         65.570           8.7       18637
3         63.277           8.7       14052
4         26.691           8.7         773
...          ...           ...         ...
8546      14.630           3.2         714
8547      10.647           3.0         543
8548      32.244           2.8        1447
8549      14.502           2.8         238
8550       9.824           2.2         215

[8551 rows x 8 columns]>

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8551 entries, 0 to 8550
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    8551 non-null   int64
 1   id            8551 non-null   int64
 2   title         8551 non-null   object
 3   overview      8531 non-null   object
 4   release_date  8551 non-null   object
 5   popularity    8551 non-null   float64
 6   vote_average  8551 non-null   float64
 7   vote_count    8551 non-null   int64
dtypes: float64(2), int64(3), object(3)
memory usage: 534.6+ KB

In [ ]:
data.isnull()

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
8546,False,False,False,False,False,False,False,False
8547,False,False,False,False,False,False,False,False
8548,False,False,False,False,False,False,False,False
8549,False,False,False,False,False,False,False,False
8550,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Unnamed: 0       0
id               0
title            0
overview        20
release_date     0
popularity       0
vote_average     0
vote_count       0
dtype: int64

In [ ]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8546    False
8547    False
8548    False
8549    False
8550    False
Length: 8551, dtype: bool

In [ ]:
data.duplicated().sum()

0

In [ ]:
data.shape

(8551, 8)

In [ ]:
data.size

68408

In [ ]:
data.dtypes

Unnamed: 0        int64
id                int64
title            object
overview         object
release_date     object
popularity      float64
vote_average    float64
vote_count        int64
dtype: object

In [ ]:
data.drop('release_date',axis=1,inplace=True)

In [ ]:
data.drop('popularity',axis=1)

,Unnamed: 0,id,title,overview,vote_average,vote_count
0,0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",8.7,2763
1,1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,8.7,1223
2,2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,8.7,18637
3,3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",8.7,14052
4,4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,8.7,773
...,...,...,...,...,...,...
8546,8546,13805,Disaster Movie,"The filmmaking team behind the hits ""Scary Mov...",3.2,714
8547,8547,5491,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",3.0,543
8548,8548,14164,Dragonball Evolution,The young warrior Son Goku sets out on a quest...,2.8,1447
8549,8549,11059,House of the Dead,"Set on an island off the coast, a techno rave ...",2.8,238
8550,8550,40016,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,2.2,215

In [ ]:
row = data.loc[2]
print(row)

Unnamed: 0                                                      2
id                                                            278
title                                    The Shawshank Redemption
overview        Framed in the 1940s for the double murder of h...
popularity                                                  65.57
vote_average                                                  8.7
vote_count                                                  18637
Name: 2, dtype: object

In [ ]:
row = data.iloc[2]
print(row)

Unnamed: 0                                                      2
id                                                            278
title                                    The Shawshank Redemption
overview        Framed in the 1940s for the double murder of h...
popularity                                                  65.57
vote_average                                                  8.7
vote_count                                                  18637
Name: 2, dtype: object

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
 sns.heatmap

<function seaborn.matrix.heatmap(data, *, vmin=None, vmax=None, cmap=None, center=None, robust=False, annot=None, fmt='.2g', annot_kws=None, linewidths=0, linecolor='white', cbar=True, cbar_kws=None, cbar_ax=None, square=False, xticklabels='auto', yticklabels='auto', mask=None, ax=None, **kwargs)>